--- #YAML:1.0
name: DateTime-Calendar-Japanese-Era
version: 0.04
author:
  - Daisuke Maki E<lt>daisuke@cpan.orgE<gt>
abstract: DateTime Extension for Japanese Eras
license: perl
requires:
  DateTime: 0
  Params::Validate: 0
recommends:
  perl: 5.6.1
build_requires: {}
conflicts: {}
provides:
  DateTime::Calendar::Japanese::Era:
    file: lib/DateTime/Calendar/Japanese/Era.pm
    version: 0.04
generated_by: Module::Build version 0.22
