---
name: DateTime-Calendar-Japanese-Era
version: 0.05
author:
  - Daisuke Maki E<lt>daisuke@cpan.orgE<gt>
abstract: DateTime Extension for Japanese Eras
license: perl
requires:
  DateTime: 0
  Params::Validate: 0
recommends:
  perl: 5.6.1
provides:
  DateTime::Calendar::Japanese::Era:
    file: lib/DateTime/Calendar/Japanese/Era.pm
    version: 0.05
generated_by: Module::Build version 0.2611
