--- 
abstract: DateTime Extension for Japanese Eras
author: 
  - Copyright (c) 2004-2007 Daisuke Maki <daisuke@endeworks.jp>
build_requires: 
  ExtUtils::MakeMaker: 6.11
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DateTime-Calendar-Japanese-Era
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  DateTime: 0
  DateTime::Infinite: 0
  Exporter: 0
  File::ShareDir: 0
  Params::Validate: 0
version: 0.08000
